### ISSUE TITLE
Original Board Question

### ISSUE THREAD

**Issue by lavachemist** [Depau/leviot-hw#1]
Hello,

I haven't pulled the Levoit 300 apart yet, but I'm curious what the original board uses. Do you have pictures of it, by any chance?

I have a couple of Levoit smart humidifiers ("Classic 200S" ASIN: B08KXW1KRJ), which have ESP32-Solo-1C chips on them. I was hoping the 300 would already be ESP based. Is it not?

-LC

**Comment by depau** [comment]
Here you go (closing since it's not an issue, feel free to continue using the thread for questions)

[![](https://slides.poul.org/2021/reverseit/air-purifier/8-got-it.jpg)](https://slides.poul.org/2021/reverseit/air-purifier/8-got-it.jpg)
[![](https://slides.poul.org/2021/reverseit/air-purifier/10-controller-top-angle.jpg)](https://slides.poul.org/2021/reverseit/air-purifier/10-controller-top-angle.jpg)
[![](https://slides.poul.org/2021/reverseit/air-purifier/11-controller-top.jpg)](https://slides.poul.org/2021/reverseit/air-purifier/11-controller-top.jpg)
[![](https://slides.poul.org/2021/reverseit/air-purifier/12-controller-bottom.jpg)](https://slides.poul.org/2021/reverseit/air-purifier/12-controller-bottom.jpg)

**Comment by depau** [comment]
Ah you may be interested in these two too:

[![](https://slides.poul.org/2021/reverseit/air-purifier/13-chip-holtek.jpg)](https://slides.poul.org/2021/reverseit/air-purifier/13-chip-holtek.jpg)
[![](https://slides.poul.org/2021/reverseit/air-purifier/14-chip-elan.jpg)](https://slides.poul.org/2021/reverseit/air-purifier/14-chip-elan.jpg)
