### ISSUE TITLE
Re: Any updates on your board

### ISSUE THREAD

**Issue by letshin** [Depau/leviot-hw#2]
Hi, I wanted to ask if you managed to test the PCB you made and how it has been functioning. Did you manage to get a new revision out of the PCB?

**Comment by depau** [comment]
Hi! Actually yes! I forgot/haven't felt like updating the readme appropriately, and i haven't tagged the new version, but the latest commits should produce the new board. You can check on kicad.

![PXL_20230510_195927271](https://github.com/depau/leviot-hw/assets/1151321/002f7de5-b891-4bc9-9961-da26152fd588)
![PXL_20230510_195935430](https://github.com/depau/leviot-hw/assets/1151321/278799e4-b805-4f6c-87a8-63c8d189bd78)

This new PCB uses surface-mount LEDs to save space and allow placing the esp32 on the side, which helps reduce noise.

Unfortunately it still has some slight issues, mostly due to the fact that I'm not an expert at PCB design and touchpads are highly sensitive to noise.

This board, once the touchpad is properly calibrated, has been doing its job for both me and @thypon for almost 1½ years.

There are two issues:

- The touchpad occasionally becomes unresponsive (but remote control works fine). I haven't figured this out yet, mostly since unplugging it solves the issue
- The filter change indicator LED is not particularly reliable (but I remember to change the filter and ignore the indicator, so I've had no incentive to look into it)

Overall it works and I could mail you my PCBs (the one in the picture) if you're willing to fetch and solder the missing components, or you can order it presoldered from one of the Chinese websites.

That being said, since they released the Wi-Fi model right after I finished up my boards, I'd recommend getting that instead since it's cheaper than getting my board manufactured. My board is more fun though :)

**Comment by depau** [comment]
Some more pics of the PCB I actually have on my purifier

![PXL_20230510_201825369](https://github.com/depau/leviot-hw/assets/1151321/dc269d8b-d7d4-46f0-beb5-87be47b93018)
![PXL_20230510_201812952](https://github.com/depau/leviot-hw/assets/1151321/d3459629-a9a4-4fe3-8fdd-6d6f813e11bc)
![PXL_20230510_201801437](https://github.com/depau/leviot-hw/assets/1151321/e0748498-2e0c-4bf9-b51e-f4def1c5e7ae)

**Comment by letshin** [comment]
Thanks for this. Can't believe its almost been a year but I didn't realise you had responded. Been looking at air filters again as we have a little one coming and have more or less settled on an Ikea one as the HA forums has some PCB designs for them that someone has put together.
